version: 1.0.{build}
before_build:
- ps: >-
    wget https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe -OutFile nuget.exe
build_script:
- cmd: >-
    nuget restore Ant.sln

    msbuild Ant.sln /m /p:Verbosity=Minimal

test_script:
  - packages\xunit.runner.console.2.1.0\tools\xunit.console.exe test\ClassicTests\bin\Debug\ClassicTests.dll